### ISSUE TITLE
Upvote/Downvote bug

### ISSUE THREAD

**Issue by systart** [MassiveNerds/RetroMatic#41]
Bug steps:
- open a board session at two different browsers
- add a new entry
- upvote entry both of them
- downvote entry at just one
vote count disappears from entry, and comes back when you vote again

**Comment by wordythebyrd** [comment]
Hey @systart, thanks for reporting this!  I was able to replicate the bug and I will take a look at it tonight.

**Comment by wordythebyrd** [comment]
The issue is we are hiding the badge for "zero" votes.  

So in this case, there's 2 +1 votes, then when you downvote from one window, it's changing a +1 vote to a -1 vote, so netting a 0.  (Not the same as clicking the upvote again to remove the upvote.)

We could update the code to display zero votes in the case that there are votes on the entry.
